// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(takehome_coreFFI)
import takehome_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_takehome_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_takehome_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * Household split for FFI
 */
public struct HouseholdSplitFfi {
    public var primaryRatio: String
    public var partnerRatio: String
    public var primaryAmount: String
    public var partnerAmount: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(primaryRatio: String, partnerRatio: String, primaryAmount: String, partnerAmount: String) {
        self.primaryRatio = primaryRatio
        self.partnerRatio = partnerRatio
        self.primaryAmount = primaryAmount
        self.partnerAmount = partnerAmount
    }
}



extension HouseholdSplitFfi: Equatable, Hashable {
    public static func ==(lhs: HouseholdSplitFfi, rhs: HouseholdSplitFfi) -> Bool {
        if lhs.primaryRatio != rhs.primaryRatio {
            return false
        }
        if lhs.partnerRatio != rhs.partnerRatio {
            return false
        }
        if lhs.primaryAmount != rhs.primaryAmount {
            return false
        }
        if lhs.partnerAmount != rhs.partnerAmount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(primaryRatio)
        hasher.combine(partnerRatio)
        hasher.combine(primaryAmount)
        hasher.combine(partnerAmount)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHouseholdSplitFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HouseholdSplitFfi {
        return
            try HouseholdSplitFfi(
                primaryRatio: FfiConverterString.read(from: &buf), 
                partnerRatio: FfiConverterString.read(from: &buf), 
                primaryAmount: FfiConverterString.read(from: &buf), 
                partnerAmount: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HouseholdSplitFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.primaryRatio, into: &buf)
        FfiConverterString.write(value.partnerRatio, into: &buf)
        FfiConverterString.write(value.primaryAmount, into: &buf)
        FfiConverterString.write(value.partnerAmount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHouseholdSplitFFI_lift(_ buf: RustBuffer) throws -> HouseholdSplitFfi {
    return try FfiConverterTypeHouseholdSplitFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHouseholdSplitFFI_lower(_ value: HouseholdSplitFfi) -> RustBuffer {
    return FfiConverterTypeHouseholdSplitFFI.lower(value)
}


/**
 * Scenario comparison for FFI
 */
public struct ScenarioComparisonFfi {
    public var base: TaxResultFfi
    public var scenario: TaxResultFfi
    public var netDifference: String
    public var monthlyDifference: String
    public var isPositive: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(base: TaxResultFfi, scenario: TaxResultFfi, netDifference: String, monthlyDifference: String, isPositive: Bool) {
        self.base = base
        self.scenario = scenario
        self.netDifference = netDifference
        self.monthlyDifference = monthlyDifference
        self.isPositive = isPositive
    }
}



extension ScenarioComparisonFfi: Equatable, Hashable {
    public static func ==(lhs: ScenarioComparisonFfi, rhs: ScenarioComparisonFfi) -> Bool {
        if lhs.base != rhs.base {
            return false
        }
        if lhs.scenario != rhs.scenario {
            return false
        }
        if lhs.netDifference != rhs.netDifference {
            return false
        }
        if lhs.monthlyDifference != rhs.monthlyDifference {
            return false
        }
        if lhs.isPositive != rhs.isPositive {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(base)
        hasher.combine(scenario)
        hasher.combine(netDifference)
        hasher.combine(monthlyDifference)
        hasher.combine(isPositive)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScenarioComparisonFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScenarioComparisonFfi {
        return
            try ScenarioComparisonFfi(
                base: FfiConverterTypeTaxResultFFI.read(from: &buf), 
                scenario: FfiConverterTypeTaxResultFFI.read(from: &buf), 
                netDifference: FfiConverterString.read(from: &buf), 
                monthlyDifference: FfiConverterString.read(from: &buf), 
                isPositive: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ScenarioComparisonFfi, into buf: inout [UInt8]) {
        FfiConverterTypeTaxResultFFI.write(value.base, into: &buf)
        FfiConverterTypeTaxResultFFI.write(value.scenario, into: &buf)
        FfiConverterString.write(value.netDifference, into: &buf)
        FfiConverterString.write(value.monthlyDifference, into: &buf)
        FfiConverterBool.write(value.isPositive, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScenarioComparisonFFI_lift(_ buf: RustBuffer) throws -> ScenarioComparisonFfi {
    return try FfiConverterTypeScenarioComparisonFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScenarioComparisonFFI_lower(_ value: ScenarioComparisonFfi) -> RustBuffer {
    return FfiConverterTypeScenarioComparisonFFI.lower(value)
}


/**
 * Tax calculation result for FFI
 */
public struct TaxResultFfi {
    public var grossAnnual: String
    public var netAnnual: String
    public var netMonthly: String
    public var netBiweekly: String
    public var netWeekly: String
    public var netDaily: String
    public var netHourly: String
    public var takeHomePercentage: String
    public var federalTax: String
    public var federalEffectiveRate: String
    public var federalMarginalRate: String
    public var stateCode: String
    public var stateIncomeTax: String
    public var stateLocalTax: String
    public var stateSdi: String
    public var stateTotalTax: String
    public var socialSecurity: String
    public var medicare: String
    public var additionalMedicare: String
    public var ficaTotal: String
    public var totalTaxes: String
    public var totalEffectiveRate: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(grossAnnual: String, netAnnual: String, netMonthly: String, netBiweekly: String, netWeekly: String, netDaily: String, netHourly: String, takeHomePercentage: String, federalTax: String, federalEffectiveRate: String, federalMarginalRate: String, stateCode: String, stateIncomeTax: String, stateLocalTax: String, stateSdi: String, stateTotalTax: String, socialSecurity: String, medicare: String, additionalMedicare: String, ficaTotal: String, totalTaxes: String, totalEffectiveRate: String) {
        self.grossAnnual = grossAnnual
        self.netAnnual = netAnnual
        self.netMonthly = netMonthly
        self.netBiweekly = netBiweekly
        self.netWeekly = netWeekly
        self.netDaily = netDaily
        self.netHourly = netHourly
        self.takeHomePercentage = takeHomePercentage
        self.federalTax = federalTax
        self.federalEffectiveRate = federalEffectiveRate
        self.federalMarginalRate = federalMarginalRate
        self.stateCode = stateCode
        self.stateIncomeTax = stateIncomeTax
        self.stateLocalTax = stateLocalTax
        self.stateSdi = stateSdi
        self.stateTotalTax = stateTotalTax
        self.socialSecurity = socialSecurity
        self.medicare = medicare
        self.additionalMedicare = additionalMedicare
        self.ficaTotal = ficaTotal
        self.totalTaxes = totalTaxes
        self.totalEffectiveRate = totalEffectiveRate
    }
}



extension TaxResultFfi: Equatable, Hashable {
    public static func ==(lhs: TaxResultFfi, rhs: TaxResultFfi) -> Bool {
        if lhs.grossAnnual != rhs.grossAnnual {
            return false
        }
        if lhs.netAnnual != rhs.netAnnual {
            return false
        }
        if lhs.netMonthly != rhs.netMonthly {
            return false
        }
        if lhs.netBiweekly != rhs.netBiweekly {
            return false
        }
        if lhs.netWeekly != rhs.netWeekly {
            return false
        }
        if lhs.netDaily != rhs.netDaily {
            return false
        }
        if lhs.netHourly != rhs.netHourly {
            return false
        }
        if lhs.takeHomePercentage != rhs.takeHomePercentage {
            return false
        }
        if lhs.federalTax != rhs.federalTax {
            return false
        }
        if lhs.federalEffectiveRate != rhs.federalEffectiveRate {
            return false
        }
        if lhs.federalMarginalRate != rhs.federalMarginalRate {
            return false
        }
        if lhs.stateCode != rhs.stateCode {
            return false
        }
        if lhs.stateIncomeTax != rhs.stateIncomeTax {
            return false
        }
        if lhs.stateLocalTax != rhs.stateLocalTax {
            return false
        }
        if lhs.stateSdi != rhs.stateSdi {
            return false
        }
        if lhs.stateTotalTax != rhs.stateTotalTax {
            return false
        }
        if lhs.socialSecurity != rhs.socialSecurity {
            return false
        }
        if lhs.medicare != rhs.medicare {
            return false
        }
        if lhs.additionalMedicare != rhs.additionalMedicare {
            return false
        }
        if lhs.ficaTotal != rhs.ficaTotal {
            return false
        }
        if lhs.totalTaxes != rhs.totalTaxes {
            return false
        }
        if lhs.totalEffectiveRate != rhs.totalEffectiveRate {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(grossAnnual)
        hasher.combine(netAnnual)
        hasher.combine(netMonthly)
        hasher.combine(netBiweekly)
        hasher.combine(netWeekly)
        hasher.combine(netDaily)
        hasher.combine(netHourly)
        hasher.combine(takeHomePercentage)
        hasher.combine(federalTax)
        hasher.combine(federalEffectiveRate)
        hasher.combine(federalMarginalRate)
        hasher.combine(stateCode)
        hasher.combine(stateIncomeTax)
        hasher.combine(stateLocalTax)
        hasher.combine(stateSdi)
        hasher.combine(stateTotalTax)
        hasher.combine(socialSecurity)
        hasher.combine(medicare)
        hasher.combine(additionalMedicare)
        hasher.combine(ficaTotal)
        hasher.combine(totalTaxes)
        hasher.combine(totalEffectiveRate)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaxResultFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaxResultFfi {
        return
            try TaxResultFfi(
                grossAnnual: FfiConverterString.read(from: &buf), 
                netAnnual: FfiConverterString.read(from: &buf), 
                netMonthly: FfiConverterString.read(from: &buf), 
                netBiweekly: FfiConverterString.read(from: &buf), 
                netWeekly: FfiConverterString.read(from: &buf), 
                netDaily: FfiConverterString.read(from: &buf), 
                netHourly: FfiConverterString.read(from: &buf), 
                takeHomePercentage: FfiConverterString.read(from: &buf), 
                federalTax: FfiConverterString.read(from: &buf), 
                federalEffectiveRate: FfiConverterString.read(from: &buf), 
                federalMarginalRate: FfiConverterString.read(from: &buf), 
                stateCode: FfiConverterString.read(from: &buf), 
                stateIncomeTax: FfiConverterString.read(from: &buf), 
                stateLocalTax: FfiConverterString.read(from: &buf), 
                stateSdi: FfiConverterString.read(from: &buf), 
                stateTotalTax: FfiConverterString.read(from: &buf), 
                socialSecurity: FfiConverterString.read(from: &buf), 
                medicare: FfiConverterString.read(from: &buf), 
                additionalMedicare: FfiConverterString.read(from: &buf), 
                ficaTotal: FfiConverterString.read(from: &buf), 
                totalTaxes: FfiConverterString.read(from: &buf), 
                totalEffectiveRate: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: TaxResultFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.grossAnnual, into: &buf)
        FfiConverterString.write(value.netAnnual, into: &buf)
        FfiConverterString.write(value.netMonthly, into: &buf)
        FfiConverterString.write(value.netBiweekly, into: &buf)
        FfiConverterString.write(value.netWeekly, into: &buf)
        FfiConverterString.write(value.netDaily, into: &buf)
        FfiConverterString.write(value.netHourly, into: &buf)
        FfiConverterString.write(value.takeHomePercentage, into: &buf)
        FfiConverterString.write(value.federalTax, into: &buf)
        FfiConverterString.write(value.federalEffectiveRate, into: &buf)
        FfiConverterString.write(value.federalMarginalRate, into: &buf)
        FfiConverterString.write(value.stateCode, into: &buf)
        FfiConverterString.write(value.stateIncomeTax, into: &buf)
        FfiConverterString.write(value.stateLocalTax, into: &buf)
        FfiConverterString.write(value.stateSdi, into: &buf)
        FfiConverterString.write(value.stateTotalTax, into: &buf)
        FfiConverterString.write(value.socialSecurity, into: &buf)
        FfiConverterString.write(value.medicare, into: &buf)
        FfiConverterString.write(value.additionalMedicare, into: &buf)
        FfiConverterString.write(value.ficaTotal, into: &buf)
        FfiConverterString.write(value.totalTaxes, into: &buf)
        FfiConverterString.write(value.totalEffectiveRate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaxResultFFI_lift(_ buf: RustBuffer) throws -> TaxResultFfi {
    return try FfiConverterTypeTaxResultFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaxResultFFI_lower(_ value: TaxResultFfi) -> RustBuffer {
    return FfiConverterTypeTaxResultFFI.lower(value)
}


/**
 * Timeframe income for FFI
 */
public struct TimeframeFfi {
    public var annual: String
    public var monthly: String
    public var biWeekly: String
    public var weekly: String
    public var daily: String
    public var hourly: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(annual: String, monthly: String, biWeekly: String, weekly: String, daily: String, hourly: String) {
        self.annual = annual
        self.monthly = monthly
        self.biWeekly = biWeekly
        self.weekly = weekly
        self.daily = daily
        self.hourly = hourly
    }
}



extension TimeframeFfi: Equatable, Hashable {
    public static func ==(lhs: TimeframeFfi, rhs: TimeframeFfi) -> Bool {
        if lhs.annual != rhs.annual {
            return false
        }
        if lhs.monthly != rhs.monthly {
            return false
        }
        if lhs.biWeekly != rhs.biWeekly {
            return false
        }
        if lhs.weekly != rhs.weekly {
            return false
        }
        if lhs.daily != rhs.daily {
            return false
        }
        if lhs.hourly != rhs.hourly {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(annual)
        hasher.combine(monthly)
        hasher.combine(biWeekly)
        hasher.combine(weekly)
        hasher.combine(daily)
        hasher.combine(hourly)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimeframeFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimeframeFfi {
        return
            try TimeframeFfi(
                annual: FfiConverterString.read(from: &buf), 
                monthly: FfiConverterString.read(from: &buf), 
                biWeekly: FfiConverterString.read(from: &buf), 
                weekly: FfiConverterString.read(from: &buf), 
                daily: FfiConverterString.read(from: &buf), 
                hourly: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: TimeframeFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.annual, into: &buf)
        FfiConverterString.write(value.monthly, into: &buf)
        FfiConverterString.write(value.biWeekly, into: &buf)
        FfiConverterString.write(value.weekly, into: &buf)
        FfiConverterString.write(value.daily, into: &buf)
        FfiConverterString.write(value.hourly, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimeframeFFI_lift(_ buf: RustBuffer) throws -> TimeframeFfi {
    return try FfiConverterTypeTimeframeFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimeframeFFI_lower(_ value: TimeframeFfi) -> RustBuffer {
    return FfiConverterTypeTimeframeFFI.lower(value)
}


public enum TaxCalcError {

    
    
    case InvalidDecimal(message: String)
    
    case InvalidFilingStatus(message: String)
    
    case InvalidState(message: String)
    
    case CalculationError(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaxCalcError: FfiConverterRustBuffer {
    typealias SwiftType = TaxCalcError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaxCalcError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidDecimal(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidFilingStatus(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .InvalidState(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .CalculationError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TaxCalcError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InvalidDecimal(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidFilingStatus(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .InvalidState(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .CalculationError(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))

        
        }
    }
}


extension TaxCalcError: Equatable, Hashable {}

extension TaxCalcError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Calculate household expense split
 */
public func calculateHouseholdSplit(primaryNet: String, partnerNet: String, sharedExpense: String, splitMethod: String)throws  -> HouseholdSplitFfi {
    return try  FfiConverterTypeHouseholdSplitFFI.lift(try rustCallWithError(FfiConverterTypeTaxCalcError.lift) {
    uniffi_takehome_core_fn_func_calculate_household_split(
        FfiConverterString.lower(primaryNet),
        FfiConverterString.lower(partnerNet),
        FfiConverterString.lower(sharedExpense),
        FfiConverterString.lower(splitMethod),$0
    )
})
}
/**
 * Calculate taxes with full breakdown
 */
public func calculateTaxes(grossIncome: String, filingStatus: String, stateCode: String, preTaxDeductions: String, postTaxDeductions: String, traditional401k: String, roth401k: String)throws  -> TaxResultFfi {
    return try  FfiConverterTypeTaxResultFFI.lift(try rustCallWithError(FfiConverterTypeTaxCalcError.lift) {
    uniffi_takehome_core_fn_func_calculate_taxes(
        FfiConverterString.lower(grossIncome),
        FfiConverterString.lower(filingStatus),
        FfiConverterString.lower(stateCode),
        FfiConverterString.lower(preTaxDeductions),
        FfiConverterString.lower(postTaxDeductions),
        FfiConverterString.lower(traditional401k),
        FfiConverterString.lower(roth401k),$0
    )
})
}
/**
 * Compare two scenarios
 */
public func compareScenarios(baseGross: String, baseFilingStatus: String, baseState: String, basePreTax: String, basePostTax: String, baseTraditional401k: String, baseRoth401k: String, scenarioGross: String, scenarioFilingStatus: String, scenarioState: String, scenarioPreTax: String, scenarioPostTax: String, scenarioTraditional401k: String, scenarioRoth401k: String)throws  -> ScenarioComparisonFfi {
    return try  FfiConverterTypeScenarioComparisonFFI.lift(try rustCallWithError(FfiConverterTypeTaxCalcError.lift) {
    uniffi_takehome_core_fn_func_compare_scenarios(
        FfiConverterString.lower(baseGross),
        FfiConverterString.lower(baseFilingStatus),
        FfiConverterString.lower(baseState),
        FfiConverterString.lower(basePreTax),
        FfiConverterString.lower(basePostTax),
        FfiConverterString.lower(baseTraditional401k),
        FfiConverterString.lower(baseRoth401k),
        FfiConverterString.lower(scenarioGross),
        FfiConverterString.lower(scenarioFilingStatus),
        FfiConverterString.lower(scenarioState),
        FfiConverterString.lower(scenarioPreTax),
        FfiConverterString.lower(scenarioPostTax),
        FfiConverterString.lower(scenarioTraditional401k),
        FfiConverterString.lower(scenarioRoth401k),$0
    )
})
}
/**
 * Convert annual amount to all timeframes
 */
public func convertTimeframes(annual: String)throws  -> TimeframeFfi {
    return try  FfiConverterTypeTimeframeFFI.lift(try rustCallWithError(FfiConverterTypeTaxCalcError.lift) {
    uniffi_takehome_core_fn_func_convert_timeframes(
        FfiConverterString.lower(annual),$0
    )
})
}
/**
 * Get list of all filing statuses
 */
public func getAllFilingStatuses() -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_takehome_core_fn_func_get_all_filing_statuses($0
    )
})
}
/**
 * Get list of all state codes
 */
public func getAllStateCodes() -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_takehome_core_fn_func_get_all_state_codes($0
    )
})
}
/**
 * Get current tax year
 */
public func getTaxYear() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_takehome_core_fn_func_get_tax_year($0
    )
})
}
/**
 * Get library version
 */
public func getVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_takehome_core_fn_func_get_version($0
    )
})
}
/**
 * Check if state has no income tax
 */
public func stateHasNoIncomeTax(stateCode: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_takehome_core_fn_func_state_has_no_income_tax(
        FfiConverterString.lower(stateCode),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_takehome_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_takehome_core_checksum_func_calculate_household_split() != 25200) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takehome_core_checksum_func_calculate_taxes() != 35304) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takehome_core_checksum_func_compare_scenarios() != 26540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takehome_core_checksum_func_convert_timeframes() != 22135) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takehome_core_checksum_func_get_all_filing_statuses() != 20825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takehome_core_checksum_func_get_all_state_codes() != 5335) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takehome_core_checksum_func_get_tax_year() != 51625) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takehome_core_checksum_func_get_version() != 42189) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_takehome_core_checksum_func_state_has_no_income_tax() != 429) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all