name: TakeHome
options:
  bundleIdPrefix: com.takehome
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  defaultConfig: Release
  disableSynthesizedResourceAccessors: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    SWIFT_STRICT_CONCURRENCY: "minimal"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"
    DEAD_CODE_STRIPPING: "YES"
    BUILD_LIBRARY_FOR_DISTRIBUTION: "NO"
    SWIFT_EMIT_LOC_STRINGS: "YES"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: "YES"
    ENABLE_MODULE_VERIFIER: "YES"
    MODULE_VERIFIER_SUPPORTED_LANGUAGES: "objective-c objective-c++"
    MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu17 gnu++20"

targets:
  TakeHome:
    type: application
    platform: iOS
    sources:
      - path: TakeHome
        excludes:
          - "**/*.xcassets"
          - "**/Info.plist"
    resources:
      - path: TakeHome/Resources/Assets.xcassets
    dependencies:
      - framework: ../bindings/TakeHomeCore.xcframework
        embed: false
        link: true
    settings:
      base:
        INFOPLIST_FILE: TakeHome/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.takehome.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OBJC_BRIDGING_HEADER: TakeHome/Core/TakeHome-Bridging-Header.h
        GENERATE_INFOPLIST_FILE: "NO"
        HEADER_SEARCH_PATHS:
          - $(inherited)
          - ../bindings/swift
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
          - "../bindings/TakeHomeCore.xcframework/ios-arm64-simulator"
          - "../bindings/TakeHomeCore.xcframework/ios-arm64"
        OTHER_LDFLAGS:
          - $(inherited)
      configs:
        Debug:
          CODE_SIGN_IDENTITY: ""
          CODE_SIGNING_REQUIRED: "NO"
          CODE_SIGNING_ALLOWED: "NO"
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          CODE_SIGN_IDENTITY: ""
          CODE_SIGNING_REQUIRED: "NO"
          CODE_SIGNING_ALLOWED: "NO"
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    preBuildScripts:
      - name: "Copy FFI Bindings"
        script: |
          cp "${PROJECT_DIR}/../bindings/swift/takehome_core.swift" "${PROJECT_DIR}/TakeHome/Core/" 2>/dev/null || true
        inputFiles:
          - $(PROJECT_DIR)/../bindings/swift/takehome_core.swift
        outputFiles:
          - $(PROJECT_DIR)/TakeHome/Core/takehome_core.swift

  TakeHomeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TakeHomeTests
    dependencies:
      - target: TakeHome
    settings:
      base:
        INFOPLIST_FILE: TakeHomeTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.takehome.tests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/TakeHome.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/TakeHome

  TakeHomeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TakeHomeUITests
    dependencies:
      - target: TakeHome
    settings:
      base:
        INFOPLIST_FILE: TakeHomeUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.takehome.uitests
        TEST_TARGET_NAME: TakeHome

schemes:
  TakeHome:
    build:
      targets:
        TakeHome: all
        TakeHomeTests: [test]
        TakeHomeUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TakeHomeTests
        - TakeHomeUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
